# In this directory, run the following command to build this builder.
# $ gcloud builds submit . --config=cloudbuild.yaml

# setup an ssh tunnel to a bastion machine so we can deploy to a private kubernetes cluster
steps:
- id: "prepare step"
  name: 'gcr.io/$PROJECT_ID/private-deploy'
  args:
    - prepare
    - -f nginx.yaml

- id: "apply step"
  name: 'gcr.io/$PROJECT_ID/private-deploy'
  args:
    - apply
    - -f nginx.yaml
    - -c $_GKE_CLUSTER_NAME
    - -l $_GKE_CLUSTER_ZONE
    - -p $PROJECT_ID
    - -n default

substitutions:
  _GKE_CLUSTER_NAME: "private-deployment-test"
  _GKE_CLUSTER_ZONE: "europe-west2-a"
