# In this directory, run the following command to build this builder.
# $ gcloud builds submit . --config=cloudbuild.yaml

# deploy to a private kubernetes cluster with a bastion machine and ssh tunnel
steps:
- id: "private-deploy cloudbuilder"
  name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "$_REPOSITORY/$PROJECT_ID/private-deploy",
                  "-t", "$_REPOSITORY/$PROJECT_ID/private-deploy:$SHORT_SHA",
         "./builder" ]

- id: "bastion privoxy container"
  name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "$_REPOSITORY/$PROJECT_ID/private-deploy-proxy",
                  "-t", "$_REPOSITORY/$PROJECT_ID/private-deploy-proxy:$SHORT_SHA",
         "./bastion-vm" ]

images:
- "$_REPOSITORY/$PROJECT_ID/private-deploy:latest"
- "$_REPOSITORY/$PROJECT_ID/private-deploy:$SHORT_SHA"
- "$_REPOSITORY/$PROJECT_ID/private-deploy-proxy:latest"
- "$_REPOSITORY/$PROJECT_ID/private-deploy-proxy:$SHORT_SHA"

tags: ["cloud-builders-community"]

substitutions:
  _REPOSITORY: eu.gcr.io
