# In this directory, run the following command to build this builder.
# $ gcloud builds submit . --config=cloudbuild.yaml

# deploy to a private kubernetes cluster with a bastion machine and ssh tunnel
steps:
- id: "private-deploy cloudbuilder"
- name: "gcr.io/cloud-builders/docker"
  args: [ "build", "-t", "gcr.io/$PROJECT_ID/private-deploy", "-t", "gcr.io/$PROJECT_ID/private-deploy:$SHORT_SHA", "./cloudbuilder" ]

- id: "bastion privoxy container"
  name: "gcr.io/cloud-builders/docker"
  args: [ "build", "-t", "gcr.io/$PROJECT_ID/private-deploy-proxy", "-t", "gcr.io/$PROJECT_ID/private-deploy-proxy:$SHORT_SHA", "./bastion-vm" ]

images:
- "gcr.io/$PROJECT_ID/private-deploy:latest"
- "gcr.io/$PROJECT_ID/private-deploy:$SHORT_SHA"
- "gcr.io/$PROJECT_ID/private-deploy-proxy:latest"
- "gcr.io/$PROJECT_ID/private-deploy-proxy:$SHORT_SHA"

tags: ["cloud-builders-community"]
