# In this directory, run the following command to build this builder.
# $ gcloud builds submit . --config=cloudbuild.yaml

# setup an ssh tunnel to a bastion machine so we can deploy to a private kubernetes cluster
steps:
- id: "apply step"
  name: 'gcr.io/$PROJECT_ID/private-deploy'
  env:
    - GKE_CLUSTER=${_GKE_CLUSTER_NAME}
    - GKE_NAMESPACE=${_GKE_NAMESPACE}
    - ZONE=${_GKE_BASTION_ZONE}
    - REGION=${_GKE_CLUSTER_REGION}
    - NETWORK=${_BASTION_NETWORK}
    - SUBNET=${_BASTION_SUBNET}
    - GOOGLE_CLOUD_PROJECT=${PROJECT_ID}
  args:
    - apply
    - -f my-deployment.yaml

substitutions:
  _GKE_CLUSTER_NAME: "private-deployment-test"
  _GKE_NAMESPACE: "default"
  _GKE_CLUSTER_REGION: europe-west2
  _BASTION_ZONE: europe-west2-a
  _BASTION_NETWORK: k8s
  _BASTION_SUBNET: nodes
  _GKE_NAMESPACE: "default"
